---
title: "test"
author: "Luke Hayden"
date: "July 30, 2016"
output: html_document
self_contained: no
---

```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
require("knitr")
opts_chunk$set(cache=TRUE, cache.path = 'test_files/', fig.path='figure/')

library("ggplot2", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2")
library("reshape2", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2")
library("ade4", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2") 
library("ecodist", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2")
library("phytools", lib.loc="~/R/x86_64-pc-linux-gnu-library/3.2")

```


#Import
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

mxstg <- read.table("mxFVBDUHiCD1scores20.txt")
mxstgmelted <- melt(mxstg, id.vars=c("ID", "Strain", "Age", "Weight", "Clutch", "shh_M2_spot", "M1_spot_split_LR", "Total_state", "stateord", "Symmetry", "groupwt"))

```


#Logistic regression
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

#logistic regression
subsmxstg <- subset(mxstg, Strain!= "CD1")
subsmxstg$shh_R2_spot <- factor(subsmxstg$shh_R2_spot > 0)
subsmxstg$Strain <- factor(subsmxstg$Strain)
mxlogitR2 <- glm(shh_R2_spot ~ Weight + Strain, data = subsmxstg, family = "binomial")
summary(mxlogitR2)

subsmxstg$shh_M1_spot <- factor(subsmxstg$shh_M1_spot > 0)
mxlogitM1 <- glm(shh_M1_spot ~ Weight + Strain, data = subsmxstg, family = "binomial")
summary(mxlogitM1)

subsmxstg$cap_transition <- factor(subsmxstg$cap_transition > 0)
mxlogitCAP <- glm(cap_transition ~ Weight + Strain, data = subsmxstg, family = "binomial")
summary(mxlogitCAP)

mxlogitSHB <- glm(shboob ~ Weight + Strain, data = subsmxstg, family = "binomial")
summary(mxlogitSHB)

```

#Graphing

#Each character in its own plot
```{r, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
ggplot(mxstgmelted, aes(x=Weight,y=value,color=Strain,shape=Strain)) +geom_point(size=1.5) + facet_wrap(~ variable,ncol=1) +  scale_y_continuous(breaks=c(0,1,2))
dev.copy(svg,'charplot.svg')
dev.off()
dev.copy(pdf,'charplot.pdf')
dev.off()
dev.copy(png,'charplot.png')
dev.off()

```

no cd1